### ISSUE TITLE
Doesn't work with TS

### ISSUE THREAD

**Issue by aadityarajkumawat** [ShaunLWM/react-animated-heart#11]
Just renders an empty div when using in typescript

**Comment by ShaunLWM** [comment]
Able to show a snippet of what you've done? Just tested in TS. It's working fine as of v0.0.8

**Comment by aadityarajkumawat** [comment]
Man, it's been a while, it was a couple of years ago, don't remember anymore 😅, I think I was making a Twitter clone.

I guess you can mark it resolved.

**Comment by ShaunLWM** [comment]
Ah so sorry about that. Was busy transitioning my life from a student to working adult 😥 totally stopped looking into the repo. Hope your project turned out good nonetheless. Enjoy your week :)
