### ISSUE TITLE
Ability to Resize?

### ISSUE THREAD

**Issue by redliz5808** [ShaunLWM/react-animated-heart#12]
Is there any way to resize this component? I've tried a couple different things (inline styles, styled components) and can't seem to get it any smaller than 100 x 100. TIA.

**Comment by ess4654** [comment]
I found a way around this. You need to place the heart into a parent div then give the parent div a css transform on the scale. This will allow you to shrink the component.

**Comment by redliz5808** [comment]
Ok, thanks! I'll give that a shot.
