### ISSUE TITLE
Doesn't seem to be working anymore

### ISSUE THREAD

**Issue by dancruznyc** [ShaunLWM/react-animated-heart#16]
I tried to install this package onto a project Im working on and it doesn't seem to be working anymore. It may have several deprecated dependencies but Im not an expert so not sure why it wasn't working. Would be great if we could get this updated. If I can help let me know.

**Comment by Alireza17224** [comment]
same !

**Comment by ShaunLWM** [comment]
Apologise for the late response. Fixed in v0.0.8. Thanks
